# MI² Education {-}

The demand for predictive modelling skills is growing at a furious rate. Part of our mission is to develop human capital so that predictive modelling is applied responsibly and safely.

We take social responsibility seriously and as part of our activities we support the development of data analysis skills among pupils, students and senior professionals alike.


## Teaching {-}

### Classes at MiNI {-}

#### 2020/2021 {-}
- [Introduction to exploratory data analysis course for Mathematics and data analysis studies in Summer](https://github.com/mini-pw/2021L-ExploratoryDataAnalysis)
  - lectures, laboratory, project - Anna Kozak
  - laboratory - *Krzysztof Spaliński* 
  
- [Case Study course for DS studies in Summer](https://github.com/mini-pw/2021L-WarsztatyBadawcze)
  - lectures - Katarzyna Woźnica
  - [XAI1](https://github.com/mini-pw/2021L-WB-XAI-1) - laboratory, project - Anna Kozak
  - [XAI2](https://github.com/mini-pw/2021L-WB-XAI-2) - laboratory, project - Szymon Maksymiuk
  - [DL1](https://github.com/mini-pw/2021L-WB-DL-1) - laboratory, project - Weronika Hryniewska
  - [DL2](https://github.com/mini-pw/2021L-WB-DL-2) - laboratory, project - Paulina Tomaszewska
  - [ML](https://github.com/mini-pw/2021L-WB-ML) - laboratory, project - Hubert Baniecki 
  - [RashomonML](https://github.com/mini-pw/2021L-WB-RashomonML) - laboratory, project - Katarzyna Woźnica

- [Data Visualization Techniques course for DS studies in Winter](https://github.com/mini-pw/2021Z-DataVisualizationTechniques)
  - lectures, laboratory - Alicja Gosiewska
  - project - Hubert Baniecki 

#### 2019/2020 {-}

- [Case Study course for DS studies in Summer](https://github.com/mini-pw/2020L-WarsztatyBadawcze)
  - lectures - Alicja Gosiewska
  - [Imputation](https://github.com/mini-pw/2020L-WarsztatyBadawcze-Imputacja) - laboratory, project - Katarzyna Woźnica
  - [Reproducibility of scientific papers](https://github.com/mini-pw/2020L-WarsztatyBadawcze-Reprodukowalnosc) - laboratory, project - Alicja Gosiewska
  - [Interpretability](https://github.com/mini-pw/2020L-WarsztatyBadawcze-InzynieriaCech) - laboratory, project - Katarzyna Kobylińska

- [Interpretable Machine Learning course in Summer](https://github.com/pbiecek/InterpretableMachineLearning2020)
  - lectures, project - Przemysław Biecek  
  
- [Data Visualization course in Summer](https://github.com/mini-pw/2020L-WizualizacjaDanych)
  - lectures, project - Michał Burdukiewicz

- [Data Visualization Techniques course for DS studies in Winter](https://github.com/mini-pw/2020Z-TechnikiWizualizacjiDanych)
  - lectures, laboratory, project - Michał Burdukiewicz
  
- [Advanced Programming in R course in Winter](https://github.com/mini-pw/2020Z-ProgramowanieWR)
  - lectures, laboratory, project - Michał Burdukiewicz
  
#### 2018/2019{-}

- [Case Study course for DS studies in Summer](https://github.com/mini-pw/2019L-WarsztatyBadawcze)
  - lectures, laboratory, project - Alicja Gosiewska

- [Data Visualization course in Summer](https://github.com/mini-pw/WizualizacjaDanych2018)
  - lectures, project - Michał Burdukiewicz
  
- [Interpretable Machine Learning course in Summer](https://github.com/pbiecek/InterpretableMachineLearning2018S)
  - lectures, project - Przemysław Biecek
  
- R Advance
  - lectures, laboratory, project - Przemysław Biecek

- [Data Visualization Techniques course for DS studies in Winter](https://github.com/pbiecek/TechnikiWizualizacjiDanych2018)
  - lectures, project - Przemysław Biecek
  - laboratory, project - Michał Burdukiewicz
  
### Classes at MIM{-}

#### 2020/2021 {-}

- [Interpretable Machine Learning course in Summer](https://github.com/pbiecek/InterpretableMachineLearning2021)
  - lectures, project - Przemysław Biecek
  
#### 2019/2020 {-}

- [Interpretable Machine Learning course in Summer](https://github.com/pbiecek/InterpretableMachineLearning2020)
  - lectures, project - Przemysław Biecek  
  
#### 2018/2019 {-}

- [Interpretable Machine Learning course in Summer](https://github.com/pbiecek/InterpretableMachineLearning2018S)
  - lectures, project - Przemysław Biecek

## Beta Bit {-} 

TODO - books, projects + StatTuba

