on:
  push:
    branches: main
    paths-ignore:
      - 'docs/**'

name: bookdown

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install pandoc and pandoc citeproc
        run: |
          brew install pandoc
      - name: Cache Renv packages
        uses: actions/cache@v1
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Cache bookdown results
        uses: actions/cache@v1
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'install.packages("ggplot2")'
          R -e 'install.packages("svglite")'    
          R -e 'install.packages("dplyr")'  
          R -e 'install.packages("kableExtra")'    
          R -e 'install.packages("corrplot")'
          R -e 'install.packages("tidyr")'   
          R -e 'install.packages("reshape2")'  
          R -e 'install.packages("bookdown")'   
          # rmarkdown v2.12 breaks the webpage like in https://github.com/pbiecek/mi2-website/commit/8ba905b
          # R -e 'install.packages("http://cran.r-project.org/src/contrib/Archive/rmarkdown/rmarkdown_2.11.tar.gz", repos=NULL, type="source")'
          # bookdown v0.25 breaks the webpage like in https://github.com/pbiecek/mi2-website/commit/9766f92
          # R -e 'install.packages("http://cran.r-project.org/src/contrib/Archive/bookdown/bookdown_0.24.tar.gz", repos=NULL, type="source")'
          # R -e 'renv::restore()' # try to fix https://github.com/pbiecek/mi2-website/actions/runs/5797765123/job/15714019153
      
      - name: Build site
        run: Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'
      
      - name: Commit results
        run: |
          git add .
          git commit  -m 'Render book' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
